name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
     - uses: actions/checkout@v2  
     - name: Python Linter
       uses: jaykv/python-linter@master
       with:
         source: "resto"
         mypy-options: false
         pylint-options: "--rcfile=setup.cfg"
         isort-options: "-w 100"
         black-options: "--line-length 100 --skip-string-normalization"